# Generated by Django 3.1.4 on 2021-01-11 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0023_book_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='read_users',
            field=models.ManyToManyField(blank=True, related_name='books_read_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books_genres', to='manager.Genre'),
        ),
        migrations.CreateModel(
            name='TableAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_aggregate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
