# Generated by Django 3.1.4 on 2021-01-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_gitinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitinfo',
            name='date',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
