# Generated by Django 3.1.4 on 2021-01-11 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0026_auto_20210111_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='gitinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='table_git_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
