# Generated by Django 3.1.4 on 2021-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_auto_20210111_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitinfo',
            name='git_login',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
